[project]
name = "telegram-news-classifier"
version = "1.0.2"
description = "A bot for Telegram that analyzes and classifies news using a pre-trained RuBERT model, simplifying news management in Telegram channels."
authors = [{ name = "NKTKLN", email = "nktkln@nktkln.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "aiogram>=3.16.0,<4.0.0",
  "telethon>=1.38.1,<2.0.0",
  "torch>=2.6.0,<3.0.0",
  "transformers>=4.48.0,<5.0.0",
  "spacy>=3.8.3,<4.0.0",
  "duckdb>=1.1.3,<2.0.0",
  "apscheduler>=3.11.0,<4.0.0",
  "pyyaml>=6.0.2,<7.0.0",
]

[build-system]
requires = ["hatchling>=1.26.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["bot"]

[tool.hatch.build.targets.sdist]
include = ["bot", "README.md", "pyproject.toml"]
