telegram:
  api_id: 1234567
  api_hash: "your_api_hash_here"  # https://my.telegram.org/auth
  phone_number: "+1234567890"
  session_name: "my_user_bot"
  chat_id: -987654321
  topics:
    - id: 101
      topic_id: 0
    - id: 102
      topic_id: 1
    - id: 103
      topic_id: 2
    - id: 104
      topic_id: 3
    - id: 105
      topic_id: 4
    - id: 106
      topic_id: 5
  channels:
    - id: 201
      name: "Some name"
    - id: 202
      name: "Some name"
    - id: 203
      name: "Some name"

sqlite:
  db_path: "user_bot_db.sqlite"
  table_name: "user_data"
  connection_timeout: 10
  cache_enabled: true

bot_settings:
  enable_logging: true
  log_level: "info"
  max_retries: 3
  default_language: "ru"

categories:
  0: "business"
  1: "it"
  2: "personal"
  3: "other"
  4: "weather"
  5: "gaming"
  6: "finances"
  7: "stuff"
  8: "political"
  9: "advertisement"
  10: "science"
  11: "moscow"

exclude_categories:
  - 1
  - 2
